@BASE_URL=http://localhost:3000/api
//hasan
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDE3MWY1ZDIzZGNlNjFiMzFmOTBmNzIiLCJpYXQiOjE2MTIxODcyMzUsImV4cCI6MTYxNDc3OTIzNX0.JplPcSlJsfE8gRpa2xqmGG3JOVTgBXBnAvoSJmlXldQ
@TOKEN_sami = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDE4MDQwMjgyNzEwMDBiZGFhY2I1YTgiLCJpYXQiOjE2MTIxODc0ODMsImV4cCI6MTYxNDc3OTQ4M30.XORgDo8HTTKpEPE6b-seSPPF04Q2ZUeRDHpPbYDu2UQ

//---------------------------------------------Kullanıcı---------
###
//kullanıcı kaydı
POST {{BASE_URL}}/users/createAccount
Content-Type: application/json

{
    "isim":"sami karaca",
    "email" : "sami@test.com",
    "userName" : "sami",
    "sifre" : "123456"
}

###
//kullanıcı kaydı 2
POST {{BASE_URL}}/users/createAccount
Content-Type: application/json

{
    "name":"harun",
    "surname":"cansu",
    "email" : "harun@test.com",
    
    "sifre" : "123456"
}

//giriş yap
###
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email" : "sami@test.com",
    "sifre" : "123456"
}

//token giriş
###
GET {{BASE_URL}}/users/login/token
Authorization: {{TOKEN_sami}}


//---------------------------------------------Ürün--------------
###
//ürün get w ID
GET {{BASE_URL}}/product/plusCounterProduct/60193fbea249b7048e0e358c
Authorization: {{TOKEN}}


###
//ürün get Search 
GET {{BASE_URL}}/product/GetSearch/ÜRÜN
Authorization: {{TOKEN}}

###
//ürün sahibi get w ID
GET {{BASE_URL}}/product/GetProductOwner/601804028271000bdaacb5a8
Authorization: {{TOKEN}}



###
//Misafir için satılan ürünler w id
GET {{BASE_URL}}/product/GetVisitorProduct/601804028271000bdaacb5a8
Authorization: {{TOKEN}}





###
//ürün Dell w ID
GET {{BASE_URL}}/product/dellProduct/601806850cb02d0c7c5ef7e6
Authorization: {{TOKEN_sami}}


//Ürün kayıt
###
POST {{BASE_URL}}/product/newProduct
Authorization: {{TOKEN_sami}}
Content-Type: application/json

{
    "productTitle" : "ÜRÜN 11",
    "productName" : "ÜRÜN 11",
    "category" : "BİL-MÜH",
    "productDetail" : "Detay 11",
    "productPrice" : 96,
    "university" : "SAÜ 11"
    
}


//Ürün güncelle
###
PATCH {{BASE_URL}}/product/updateProduct/601806850cb02d0c7c5ef7e6
Authorization: {{TOKEN}}
Content-Type: application/json

{
    "productTitle" : "ÜRÜN Title güncelle",
    "productName" : "ÜRÜN İSİM güncelle",
    "category" : "ELEK-MÜH",
    "productDetail" : "Detay açıklaması güncelle",
    "productPrice" : 75,
    "university" : "SAÜ güncelle",
    "situation":false
}


###
//ürün son eklenen 10 getir
GET {{BASE_URL}}/product/GetTenLastProduct
Authorization: {{TOKEN}}


###
//en çok tıklanan 10 ürünü getir
GET {{BASE_URL}}/product/GetTenMostProduct
Authorization: {{TOKEN}}




//---------------------------------------------Favoriler--------------
###
//Favorite get 
GET {{BASE_URL}}/favorite/getFavorite
Authorization: {{TOKEN}}

###
//Favorite add 
GET {{BASE_URL}}/favorite/addFavorite/60193f98a249b7048e0e3586
Authorization: {{TOKEN}}


###
//Favorite delete 
GET {{BASE_URL}}/favorite/deleteFavorite/60186fc201c9560940527621
Authorization: {{TOKEN}}
